---
# tasks file for ansible-mutillidae

# NOT IDEMPOTENT
#- name: update APT cache
#  apt:
#    update_cache: yes

- name: install Apache2
  apt:
    name: apache2
    state: present

- name: install PHP
  apt:
    name: php
    state: present

- name: install libapache2-mod-php
  apt:
    name: libapache2-mod-php
    state: present

- name: install mysql-server
  apt:
    name: ["mysql-server", "php-mysql"]
    state: present

...
